### PR TITLE
Fixing per year contribution count

### LINKED ISSUE #65: year count is always 0
The total count of all time is correct, but the count per year is always 0

image

### PR DESCRIPTION
**Pull request by LoaderB0T**
Fixes #65 by using the year.total instead of the custom calculation that seems to be broken.

### CODE REVIEW

**Comment by sallar** [comment]
Thanks @LoaderB0T , I will merge and deploy this

**Comment by LoaderB0T** [comment]
HI @sallar , any update on this?

**Comment by LoaderB0T** [comment]
Hey @sallar I don't want to be that annoying guy pinging you and pushing you to do more voluntary work - yet here we are 😅

It would be nice to see this merged & released :)

**Comment by sallar** [comment]
@LoaderB0T Im not sure why I forgot about this. let me check

**Comment by sallar** [comment]
ah I remember, because I have to use the library in the app itself. I will merge this @LoaderB0T and release it soon

**Comment by sallar** [comment]
Deployed

**Pull request merged**
